# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: jhipstersamplegateway
services:
  zipkin:
    image: openzipkin/zipkin:2.24
    ports:
      - 127.0.0.1:9411:9411
